server:
  port: 8091
spring:
  application:
    name: consumer-demo
eureka:
  client:
    service-url: # EurekaServer地址
      defaultZone: http://127.0.0.1:8761/eureka
  instance:
    prefer-ip-address: true # 当调用getHostname获取实例的hostname时，返回ip而不是host名称
    ip-address: 127.0.0.1 # 指定自己的ip信息，不指定的话会自己寻找
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 3000 # 服务请求超时自动降级时间
